//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1434
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZSS.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ZSS.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %t-%mo.%d.%y-%h.%mi.%s%pm.
        /// </summary>
        internal static string activeWindowDefault {
            get {
                return ResourceManager.GetString("activeWindowDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Program Files\Adobe\Adobe Photoshop CS2\Photoshop.exe.
        /// </summary>
        internal static string CS2 {
            get {
                return ResourceManager.GetString("CS2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SS-%mo.%d.%y-%h.%mi.%s%pm.
        /// </summary>
        internal static string entireScreenDefault {
            get {
                return ResourceManager.GetString("entireScreenDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string FTPsuccess {
            get {
                return ResourceManager.GetString("FTPsuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testing....
        /// </summary>
        internal static string FTPtest {
            get {
                return ResourceManager.GetString("FTPtest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\WINDOWS\system32\mspaint.exe.
        /// </summary>
        internal static string MSPaint {
            get {
                return ResourceManager.GetString("MSPaint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Account.
        /// </summary>
        internal static string NewAccount {
            get {
                return ResourceManager.GetString("NewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Program Files\Paint.NET\PaintDotNet.exe.
        /// </summary>
        internal static string PaintNet {
            get {
                return ResourceManager.GetString("PaintNet", resourceCulture);
            }
        }
        
        internal static bool PMvisible {
            get {
                object obj = ResourceManager.GetObject("PMvisible", resourceCulture);
                return ((bool)(obj));
            }
        }
    }
}
